id = "robot-framework"
name = "Robot Framework"
version = "0.0.1"
schema_version = 1
authors = ["José Mendes <mendesfilho@pm.me>"]
description = "🤖 Robot Framework support."
repository = "https://github.com/mendes-jose/zed-robot.git"

[grammars.robot]
repository = "https://github.com/Hubro/tree-sitter-robot"
rev = "b317756ae0fb90ca945f900c77cdd3513d0c0eb4"
