id = "robot-framework"
name = "Robot Framework"
version = "0.0.1"
schema_version = 1
authors = ["José Mendes <mendesfilho@pm.me>"]
description = "🤖 Robot Framework support."
repository = "https://github.com/mendes-jose/zed-robot.git"

[grammars.robot]
repository = "https://github.com/Hubro/tree-sitter-robot"
rev = "6bacedb56c9716e155b330f6e50084d7999f635e" # v1.5.0
